// Generated by scripts/build-sheet-setup.mjs. Do not edit directly.
const JOB_PIPELINE_SETUP = {
  "activeSheet": "Sheet1",
  "archiveSheet": "Archive",
  "claimsSheet": "ProcessingClaims",
  "dashboardSheet": "Dashboard",
  "recordFields": [
    "source",
    "source_job_id",
    "canonical_job_id",
    "state_guard",
    "canonical_url",
    "job_title",
    "company",
    "job_description",
    "salary_text",
    "posted_at",
    "discovered_at",
    "last_seen_at",
    "search_queries",
    "role_families",
    "source_availability",
    "match_score",
    "match_tier",
    "match_decision",
    "match_reasons",
    "requirement_gaps",
    "profile_version",
    "evaluated_at",
    "pipeline_status",
    "processing_stage",
    "processing_token",
    "processing_started_at",
    "attempt_count",
    "failed_stage",
    "next_retry_at",
    "error_category",
    "error_summary",
    "generated_message",
    "message_profile_version",
    "message_validation_status",
    "generated_at",
    "manual_action",
    "application_decision",
    "application_decided_at",
    "outcome",
    "outcome_at",
    "created_at",
    "updated_at",
    "archived_at",
    "archived_from_status",
    "notes"
  ],
  "legacyStatusMapping": {
    "pending": "discovered",
    "processing": "evaluating",
    "ready": "ready",
    "applied": "applied",
    "skipped": "skipped",
    "error": "terminal_error"
  },
  "legacyHeaderMapping": {
    "created_at ": "created_at",
    "job_url": "canonical_url",
    "status": "pipeline_status"
  },
  "dashboardFields": [
    "metric_key",
    "generated_at",
    "total_unique_jobs",
    "discovered",
    "recommended",
    "review_required",
    "ready",
    "applied",
    "skipped",
    "replied",
    "interview",
    "offer",
    "rejected",
    "retryable_error",
    "terminal_error",
    "unavailable"
  ],
  "claimFields": [
    "canonical_job_id",
    "processing_stage",
    "processing_token",
    "created_at",
    "expires_at"
  ],
  "reviewColumns": [
    "job_title",
    "company",
    "canonical_url",
    "posted_at",
    "salary_text",
    "role_families",
    "search_queries",
    "match_score",
    "match_tier",
    "match_reasons",
    "requirement_gaps",
    "source_availability",
    "pipeline_status",
    "processing_stage",
    "error_summary",
    "generated_message",
    "message_profile_version",
    "manual_action",
    "application_decision",
    "application_decided_at",
    "outcome",
    "outcome_at",
    "canonical_job_id",
    "state_guard",
    "processing_token",
    "profile_version",
    "created_at",
    "last_seen_at",
    "updated_at"
  ],
  "hiddenColumns": [
    "state_guard",
    "processing_token"
  ],
  "manualActions": [
    "",
    "promote",
    "mark_applied",
    "mark_skipped",
    "retry",
    "regenerate",
    "outcome_no_response",
    "outcome_replied",
    "outcome_interview",
    "outcome_offer",
    "outcome_rejected",
    "clear_outcome"
  ],
  "editableColumns": [
    "manual_action",
    "notes"
  ]
};

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Job Pipeline')
    .addItem('Set up or migrate sheets', 'setupJobPipelineSheets')
    .addItem('Sort priority queue', 'sortPriorityQueue')
    .addToUi();
}

function setupJobPipelineSheets() {
  const spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  const active = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.activeSheet, JOB_PIPELINE_SETUP.recordFields);
  const archive = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.archiveSheet, JOB_PIPELINE_SETUP.recordFields);
  const claims = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.claimsSheet, JOB_PIPELINE_SETUP.claimFields);
  const dashboard = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.dashboardSheet, JOB_PIPELINE_SETUP.dashboardFields);

  migrateLegacyCreatedAt_(active);
  migrateLegacyCreatedAt_(archive);
  migrateLegacyIdentityAndState_(active);
  migrateLegacyIdentityAndState_(archive);
  orderReviewColumns_(active);
  orderReviewColumns_(archive);
  applyReviewLayout_(active);
  applyReviewLayout_(archive);
  formatInternalSheet_(claims);
  formatInternalSheet_(dashboard);

  SpreadsheetApp.flush();
  const duplicateActiveIds = duplicateCanonicalIds_(active);
  const duplicateArchiveIds = duplicateCanonicalIds_(archive);
  if (duplicateActiveIds.length || duplicateArchiveIds.length) {
    throw new Error(
      'Canonical identity collisions require manual reconciliation before workflow activation. ' +
      'Sheet1: ' + duplicateActiveIds.join(', ') +
      '; Archive: ' + duplicateArchiveIds.join(', ')
    );
  }
  return {
    activeRows: active.getLastRow(),
    archiveRows: archive.getLastRow(),
    activeColumns: active.getLastColumn(),
    archiveColumns: archive.getLastColumn()
  };
}

function duplicateCanonicalIds_(sheet) {
  if (sheet.getLastRow() < 2) return [];
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const idColumn = headers.indexOf('canonical_job_id') + 1;
  if (idColumn < 1) return [];
  const values = sheet
    .getRange(2, idColumn, sheet.getLastRow() - 1, 1)
    .getDisplayValues()
    .flat()
    .filter(Boolean);
  const seen = new Set();
  const duplicates = new Set();
  values.forEach((value) => {
    if (seen.has(value)) duplicates.add(value);
    seen.add(value);
  });
  return [...duplicates];
}

function ensureSheet_(spreadsheet, name, requiredHeaders) {
  const sheet = spreadsheet.getSheetByName(name) || spreadsheet.insertSheet(name);
  const existingWidth = Math.max(sheet.getLastColumn(), 1);
  const existing = sheet.getRange(1, 1, 1, existingWidth).getDisplayValues()[0];
  const headers = existing.every((value) => !value) ? [] : existing;
  const missing = requiredHeaders.filter((header) => !headers.includes(header));
  const merged = headers.concat(missing);
  if (merged.length > 0) {
    sheet.getRange(1, 1, 1, merged.length).setValues([merged]);
  }
  sheet.setFrozenRows(1);
  return sheet;
}

function migrateLegacyCreatedAt_(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const legacyIndex = headers.indexOf('created_at ');
  const canonicalIndex = headers.indexOf('created_at');
  if (legacyIndex < 0 || canonicalIndex < 0 || sheet.getLastRow() < 2) return;

  const rowCount = sheet.getLastRow() - 1;
  const legacy = sheet.getRange(2, legacyIndex + 1, rowCount, 1).getValues();
  const canonicalRange = sheet.getRange(2, canonicalIndex + 1, rowCount, 1);
  const canonical = canonicalRange.getValues();
  const merged = canonical.map((row, index) => [row[0] || legacy[index][0] || '']);
  canonicalRange.setValues(merged);
}

function migrateLegacyIdentityAndState_(sheet) {
  if (sheet.getLastRow() < 2) return;
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const headerIndex = Object.fromEntries(headers.map((header, index) => [header, index]));
  const rows = sheet
    .getRange(2, 1, sheet.getLastRow() - 1, sheet.getLastColumn())
    .getValues();
  const targets = [
    'source',
    'source_job_id',
    'canonical_job_id',
    'canonical_url',
    'pipeline_status',
    'application_decision',
    'archived_from_status',
    'profile_version',
    'message_profile_version',
    'state_guard'
  ];
  const output = Object.fromEntries(targets.map((target) => [target, []]));
  const value = (row, header) =>
    headerIndex[header] === undefined ? '' : row[headerIndex[header]];

  rows.forEach((row) => {
    const hasJob = [
      'canonical_job_id',
      'canonical_url',
      'job_url',
      'source_job_id',
      'job_title'
    ].some((header) => String(value(row, header) || '').trim());
    const current = Object.fromEntries(targets.map((target) => [target, value(row, target)]));
    if (!hasJob) {
      targets.forEach((target) => output[target].push([current[target]]));
      return;
    }

    const source = String(current.source || 'onlinejobs.ph').trim().toLowerCase();
    const canonicalUrl =
      String(current.canonical_url || '').trim() ||
      normalizeLegacyUrl_(value(row, 'job_url'));
    const sourceJobId =
      String(current.source_job_id || '').trim() ||
      (canonicalUrl.match(//jobseekers/job/[^/]*?(d+)$/i) || [])[1] ||
      '';
    const canonicalJobId =
      String(current.canonical_job_id || '').trim() ||
      (sourceJobId
        ? source + ':' + sourceJobId
        : canonicalUrl
          ? source + ':url:' + fnv32_(canonicalUrl)
          : '');
    const legacyStatus = String(value(row, 'status') || '').trim().toLowerCase();
    const mappedLegacyStatus =
      JOB_PIPELINE_SETUP.legacyStatusMapping[legacyStatus] || legacyStatus || 'discovered';
    let pipelineStatus = String(current.pipeline_status || '').trim() || mappedLegacyStatus;
    let archivedFromStatus = String(current.archived_from_status || '').trim();
    if (
      sheet.getName() === JOB_PIPELINE_SETUP.archiveSheet &&
      !String(current.pipeline_status || '').trim()
    ) {
      archivedFromStatus = archivedFromStatus || mappedLegacyStatus;
      pipelineStatus = 'archived';
    }
    const applicationDecision =
      String(current.application_decision || '').trim() ||
      (archivedFromStatus === 'applied' || pipelineStatus === 'applied'
        ? 'applied'
        : archivedFromStatus === 'skipped' || pipelineStatus === 'skipped'
          ? 'skipped'
          : '');
    const outcome = String(value(row, 'outcome') || '').trim();
    const generatedMessage = String(value(row, 'generated_message') || '');
    const profileVersion = String(current.profile_version || '').trim() || 'legacy/unknown';
    const messageProfileVersion =
      String(current.message_profile_version || '').trim() ||
      (generatedMessage ? 'legacy/unknown' : '');
    const stateGuard = canonicalJobId
      ? stateGuard_(canonicalJobId, pipelineStatus, applicationDecision, outcome)
      : '';
    const migrated = {
      source,
      source_job_id: sourceJobId,
      canonical_job_id: canonicalJobId,
      canonical_url: canonicalUrl,
      pipeline_status: pipelineStatus,
      application_decision: applicationDecision,
      archived_from_status: archivedFromStatus,
      profile_version: profileVersion,
      message_profile_version: messageProfileVersion,
      state_guard: stateGuard
    };
    targets.forEach((target) => output[target].push([migrated[target]]));
  });

  targets.forEach((target) => {
    const column = headerIndex[target];
    if (column !== undefined) {
      sheet.getRange(2, column + 1, rows.length, 1).setValues(output[target]);
    }
  });
}

function normalizeLegacyUrl_(value) {
  let url = String(value || '').trim();
  if (!url) return '';
  if (url.startsWith('/')) url = 'https://onlinejobs.ph' + url;
  url = url
    .replace(/^http:///i, 'https://')
    .replace(/^https://www.onlinejobs.ph/i, 'https://onlinejobs.ph')
    .split(/[?#]/)[0]
    .replace(//+$/, '');
  return /^https://onlinejobs.ph/jobseekers/job//i.test(url) ? url : '';
}

function stateGuard_(canonicalJobId, pipelineStatus, applicationDecision, outcome) {
  return (
    canonicalJobId +
    '|' +
    fnv32_(
      [canonicalJobId, pipelineStatus, applicationDecision, outcome].join(
        String.fromCharCode(31)
      )
    )
  );
}

function fnv32_(value) {
  let hash = 2166136261;
  String(value).split('').forEach((character) => {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  });
  return (hash >>> 0).toString(16).padStart(8, '0');
}

function orderReviewColumns_(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  let destination = 1;
  JOB_PIPELINE_SETUP.reviewColumns.forEach((header) => {
    const currentIndex = headers.indexOf(header);
    if (currentIndex < 0) return;
    if (currentIndex + 1 !== destination) {
      sheet.moveColumns(
        sheet.getRange(1, currentIndex + 1, sheet.getMaxRows(), 1),
        destination
      );
      const [moved] = headers.splice(currentIndex, 1);
      headers.splice(destination - 1, 0, moved);
    }
    destination += 1;
  });
}

function applyReviewLayout_(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const actionColumn = headers.indexOf('manual_action') + 1;
  if (actionColumn > 0) {
    const validation = SpreadsheetApp.newDataValidation()
      .requireValueInList(JOB_PIPELINE_SETUP.manualActions, true)
      .setAllowInvalid(false)
      .setHelpText('Choose a supported Job Pipeline action. The reviewer workflow validates the state transition.')
      .build();
    sheet.getRange(2, actionColumn, Math.max(sheet.getMaxRows() - 1, 1), 1).setDataValidation(validation);
  }

  const statusColumn = headers.indexOf('pipeline_status') + 1;
  if (statusColumn > 0) {
    const range = sheet.getRange(2, statusColumn, Math.max(sheet.getMaxRows() - 1, 1), 1);
    const rules = [
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="ready"', '#d9ead3'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="recommended"', '#cfe2f3'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="review_required"', '#fff2cc'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="retryable_error"', '#f4cccc'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="unavailable"', '#d9d9d9')
    ];
    const unrelatedRules = sheet.getConditionalFormatRules().filter((rule) =>
      rule.getRanges().every(
        (ruleRange) =>
          ruleRange.getSheet().getSheetId() !== sheet.getSheetId() ||
          statusColumn < ruleRange.getColumn() ||
          statusColumn > ruleRange.getLastColumn()
      )
    );
    sheet.setConditionalFormatRules(unrelatedRules.concat(rules));
  }

  const messageColumn = headers.indexOf('generated_message') + 1;
  if (messageColumn > 0) {
    sheet.setColumnWidth(messageColumn, 420);
    sheet.getRange(2, messageColumn, Math.max(sheet.getMaxRows() - 1, 1), 1).setWrap(true);
  }
  const titleColumn = headers.indexOf('job_title') + 1;
  if (titleColumn > 0) sheet.setColumnWidth(titleColumn, 260);
  const urlColumn = headers.indexOf('canonical_url') + 1;
  if (urlColumn > 0) sheet.setColumnWidth(urlColumn, 260);
  ['match_reasons', 'requirement_gaps', 'notes'].forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) {
      sheet.setColumnWidth(column, 280);
      sheet.getRange(2, column, Math.max(sheet.getMaxRows() - 1, 1), 1).setWrap(true);
    }
  });
  JOB_PIPELINE_SETUP.hiddenColumns.forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) sheet.hideColumns(column);
  });
  sheet.setFrozenColumns(Math.min(3, sheet.getLastColumn()));
  sheet.getRange(1, 1, 1, sheet.getLastColumn()).setFontWeight('bold').setBackground('#1f4e78').setFontColor('#ffffff');

  removeGeneratedProtections_(sheet);
  headers.forEach((header, index) => {
    if (!JOB_PIPELINE_SETUP.editableColumns.includes(header)) {
      const protection = sheet
        .getRange(2, index + 1, Math.max(sheet.getMaxRows() - 1, 1), 1)
        .protect()
        .setDescription('Job Pipeline generated field: ' + header);
      protection.setWarningOnly(true);
    }
  });
}

function formatInternalSheet_(sheet) {
  sheet.getRange(1, 1, 1, sheet.getLastColumn()).setFontWeight('bold').setBackground('#666666').setFontColor('#ffffff');
  sheet.autoResizeColumns(1, sheet.getLastColumn());
}

function removeGeneratedProtections_(sheet) {
  sheet.getProtections(SpreadsheetApp.ProtectionType.RANGE).forEach((protection) => {
    if ((protection.getDescription() || '').startsWith('Job Pipeline generated field:')) {
      protection.remove();
    }
  });
}

function conditionalRule_(range, formula, color) {
  return SpreadsheetApp.newConditionalFormatRule()
    .whenFormulaSatisfied(formula)
    .setBackground(color)
    .setRanges([range])
    .build();
}

function sortPriorityQueue() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(JOB_PIPELINE_SETUP.activeSheet);
  if (!sheet || sheet.getLastRow() < 3) return;
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const scoreColumn = headers.indexOf('match_score') + 1;
  const postedColumn = headers.indexOf('posted_at') + 1;
  if (scoreColumn < 1 || postedColumn < 1) throw new Error('match_score and posted_at columns are required');
  sheet.getRange(2, 1, sheet.getLastRow() - 1, sheet.getLastColumn()).sort([
    { column: scoreColumn, ascending: false },
    { column: postedColumn, ascending: false }
  ]);
}

function columnLetter_(column) {
  let value = column;
  let result = '';
  while (value > 0) {
    const remainder = (value - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    value = Math.floor((value - 1) / 26);
  }
  return result;
}
