// Generated by scripts/build-sheet-setup.mjs. Do not edit directly.
const JOB_PIPELINE_SETUP = {
  "activeSheet": "Sheet1",
  "archiveSheet": "Archive",
  "reviewQueue": {
    "version": "2026-07-29/v2",
    "sheet": "Review Queue",
    "visible_columns": [
      "Status",
      "Job title",
      "Company",
      "Score",
      "Reason for review",
      "Generated message",
      "Job link",
      "Action"
    ],
    "hidden_columns": [
      "canonical_job_id",
      "source_state_guard"
    ],
    "fields": [
      "Status",
      "Job title",
      "Company",
      "Score",
      "Reason for review",
      "Generated message",
      "Job link",
      "Action",
      "canonical_job_id",
      "source_state_guard"
    ],
    "statuses": [
      "ready",
      "recommended",
      "review_required"
    ],
    "generation_recovery": {
      "statuses": [
        "retryable_error",
        "terminal_error"
      ],
      "failed_stage": "generation"
    },
    "actions": {
      "Generate Application": "promote",
      "I Applied": "mark_applied",
      "Skip": "mark_skipped"
    },
    "reason_maximum_length": 500
  },
  "appliedJobs": {
    "version": "2026-07-29/v1",
    "sheet": "Applied Jobs",
    "visible_columns": [
      "Applied at",
      "Job title",
      "Company",
      "Generated message",
      "Job link",
      "Current outcome",
      "Outcome updated at",
      "Action"
    ],
    "hidden_columns": [
      "canonical_job_id",
      "source_state_guard"
    ],
    "fields": [
      "Applied at",
      "Job title",
      "Company",
      "Generated message",
      "Job link",
      "Current outcome",
      "Outcome updated at",
      "Action",
      "canonical_job_id",
      "source_state_guard"
    ],
    "application_decision": "applied",
    "actions": {
      "No Response": "outcome_no_response",
      "Replied": "outcome_replied",
      "Interview": "outcome_interview",
      "Offer": "outcome_offer",
      "Rejected": "outcome_rejected",
      "Clear Outcome": "clear_outcome"
    },
    "sort": [
      {
        "field": "application_decided_at",
        "direction": "desc"
      },
      {
        "field": "canonical_job_id",
        "direction": "asc"
      }
    ]
  },
  "claimsSheet": "ProcessingClaims",
  "dashboardSheet": "Dashboard",
  "analyticsSheet": "Analytics",
  "analyticsReportsSheet": "AnalyticsReports",
  "recommendationsSheet": "Recommendations",
  "recommendationReportsSheet": "RecommendationReports",
  "recordFields": [
    "source",
    "source_job_id",
    "canonical_job_id",
    "state_guard",
    "processing_commit_guard",
    "canonical_url",
    "job_title",
    "company",
    "job_description",
    "salary_text",
    "posted_at",
    "discovered_at",
    "last_seen_at",
    "search_queries",
    "role_families",
    "source_availability",
    "match_score",
    "match_tier",
    "match_decision",
    "match_reasons",
    "requirement_gaps",
    "qualification_score",
    "opportunity_score",
    "ranking_confidence",
    "apply_points_recommendation",
    "ranking_factors",
    "ranking_missing_signals",
    "requirement_gap_details",
    "scoring_policy_version",
    "profile_version",
    "evaluated_at",
    "pipeline_status",
    "processing_stage",
    "processing_token",
    "processing_started_at",
    "attempt_count",
    "failed_stage",
    "next_retry_at",
    "error_category",
    "error_summary",
    "generated_message",
    "message_profile_version",
    "message_policy_version",
    "message_validation_status",
    "generated_at",
    "application_instructions",
    "screening_questions",
    "selected_proof_refs",
    "application_warnings",
    "application_pack_status",
    "application_pack_version",
    "application_pack_profile_version",
    "application_pack_policy_version",
    "application_pack_generated_at",
    "alert_status",
    "alert_channel",
    "alert_policy_version",
    "alert_idempotency_key",
    "alert_attempt_count",
    "alert_last_attempt_at",
    "alert_next_retry_at",
    "alert_sent_at",
    "alert_provider_reference",
    "alert_error_category",
    "alert_error_summary",
    "alert_suppressed_reason",
    "apply_points_input",
    "application_message_strategy_input",
    "manual_action",
    "first_reviewed_at",
    "application_decision",
    "application_decided_at",
    "apply_points_used",
    "application_message_strategy",
    "application_qualification_score",
    "application_opportunity_score",
    "application_ranking_confidence",
    "application_scoring_policy_version",
    "application_apply_points_recommendation",
    "application_pack_status_at_apply",
    "application_posting_age_days",
    "application_snapshot_at",
    "outcome",
    "outcome_at",
    "outcome_events",
    "created_at",
    "updated_at",
    "archived_at",
    "archived_from_status",
    "notes"
  ],
  "legacyStatusMapping": {
    "pending": "discovered",
    "processing": "evaluating",
    "ready": "ready",
    "applied": "applied",
    "skipped": "skipped",
    "error": "terminal_error"
  },
  "legacyHeaderMapping": {
    "created_at ": "created_at",
    "job_url": "canonical_url",
    "status": "pipeline_status"
  },
  "dashboardFields": [
    "metric_key",
    "generated_at",
    "total_unique_jobs",
    "discovered",
    "recommended",
    "review_required",
    "ready",
    "applied",
    "skipped",
    "replied",
    "interview",
    "offer",
    "rejected",
    "retryable_error",
    "terminal_error",
    "unavailable"
  ],
  "analyticsFields": [
    "analytics_row_id",
    "report_id",
    "metric_definition_version",
    "band_version",
    "generated_at",
    "window_type",
    "window_start_at",
    "window_end_at",
    "section",
    "dimension",
    "segment_key",
    "segment_label",
    "metric_key",
    "numerator",
    "denominator",
    "value",
    "unit",
    "sample_size",
    "coverage_numerator",
    "coverage_denominator",
    "attribution",
    "non_additive",
    "note"
  ],
  "analyticsReportFields": [
    "report_id",
    "status",
    "metric_definition_version",
    "band_version",
    "generated_at",
    "window_type",
    "window_start_at",
    "window_end_at",
    "analysis_timezone",
    "record_count",
    "application_count",
    "detail_row_count",
    "attribution_policy",
    "warning_summary"
  ],
  "recommendationFields": [
    "recommendation_id",
    "run_id",
    "analysis_key",
    "analytics_report_id",
    "recommendation_policy_version",
    "metric_definition_version",
    "band_version",
    "generated_at",
    "window_start_at",
    "window_end_at",
    "status",
    "category",
    "affected_type",
    "affected_key",
    "direction",
    "title",
    "evidence_metric",
    "numerator",
    "denominator",
    "sample_size",
    "comparison_value",
    "baseline_value",
    "difference",
    "coverage_numerator",
    "coverage_denominator",
    "coverage_rate",
    "proposed_operator_action",
    "caveat"
  ],
  "recommendationReportFields": [
    "run_id",
    "analysis_key",
    "status",
    "result",
    "recommendation_policy_version",
    "analytics_report_id",
    "metric_definition_version",
    "band_version",
    "generated_at",
    "window_start_at",
    "window_end_at",
    "minimum_overall_applications",
    "minimum_segment_applications",
    "minimum_explicit_outcome_coverage",
    "recommendation_count",
    "abstention_count",
    "detail_row_count",
    "error_category",
    "error_summary"
  ],
  "versionFields": [
    "alert_policy_version",
    "application_pack_policy_version",
    "application_pack_profile_version",
    "application_pack_version",
    "application_scoring_policy_version",
    "band_version",
    "message_policy_version",
    "message_profile_version",
    "metric_definition_version",
    "profile_version",
    "recommendation_policy_version",
    "scoring_policy_version"
  ],
  "maximumClaimLeaseMs": 600000,
  "currentMessageVersions": {
    "profile_version": "2026-07-29",
    "message_policy_version": "2026-07-28",
    "pack_version": "2026-07-28/v1",
    "pack_policy_version": "2026-07-28/v1"
  },
  "claimFields": [
    "canonical_job_id",
    "processing_stage",
    "processing_token",
    "created_at",
    "expires_at"
  ],
  "reviewColumns": [
    "job_title",
    "company",
    "canonical_url",
    "posted_at",
    "salary_text",
    "role_families",
    "search_queries",
    "qualification_score",
    "opportunity_score",
    "ranking_confidence",
    "apply_points_recommendation",
    "match_score",
    "match_tier",
    "match_reasons",
    "requirement_gaps",
    "requirement_gap_details",
    "ranking_missing_signals",
    "source_availability",
    "pipeline_status",
    "processing_stage",
    "error_summary",
    "generated_message",
    "manual_action",
    "canonical_job_id",
    "state_guard",
    "processing_commit_guard",
    "processing_token",
    "apply_points_input",
    "application_message_strategy_input",
    "application_pack_status",
    "application_instructions",
    "screening_questions",
    "selected_proof_refs",
    "application_warnings",
    "application_pack_version",
    "application_pack_profile_version",
    "application_pack_policy_version",
    "application_pack_generated_at",
    "message_profile_version",
    "application_decision",
    "application_decided_at",
    "outcome",
    "outcome_at",
    "ranking_factors",
    "scoring_policy_version",
    "profile_version",
    "created_at",
    "last_seen_at",
    "updated_at"
  ],
  "hiddenColumns": [
    "state_guard",
    "processing_commit_guard",
    "processing_token"
  ],
  "manualActions": [
    "",
    "mark_reviewed",
    "promote",
    "mark_applied",
    "mark_skipped",
    "retry",
    "regenerate",
    "outcome_no_response",
    "outcome_replied",
    "outcome_interview",
    "outcome_offer",
    "outcome_rejected",
    "clear_outcome"
  ],
  "editableColumns": [
    "apply_points_input",
    "application_message_strategy_input",
    "manual_action",
    "notes"
  ],
  "reviewInputRules": {
    "applyPoints": {
      "type": "integer",
      "minimum": 1,
      "maximum": 60,
      "nullable": true
    },
    "messageStrategy": {
      "type": "string",
      "maximum_length": 64,
      "pattern": "^[a-z0-9][a-z0-9._-]{0,47}/v[1-9][0-9]{0,5}$",
      "nullable": true
    }
  }
};

const LEGACY_MESSAGE_QUARANTINE_IDS = [
  "onlinejobs.ph:1696828",
  "onlinejobs.ph:1696881",
  "onlinejobs.ph:1585711",
  "onlinejobs.ph:1697174",
  "onlinejobs.ph:1697248",
  "onlinejobs.ph:1697386",
  "onlinejobs.ph:1697330",
  "onlinejobs.ph:1697526"
];

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Job Pipeline')
    .addItem('Set up or migrate sheets', 'setupJobPipelineSheets')
    .addItem('Sort priority queue', 'sortPriorityQueue')
    .addToUi();
  const reviewQueue = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(
    JOB_PIPELINE_SETUP.reviewQueue.sheet
  );
  if (reviewQueue) applyReviewQueueActionValidation_(reviewQueue);
  const appliedJobs = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(
    JOB_PIPELINE_SETUP.appliedJobs.sheet
  );
  if (appliedJobs) applyAppliedJobsActionValidation_(appliedJobs);
}

function onSelectionChange(event) {
  const range = event && event.range;
  if (!range) return;
  const sheet = range.getSheet();
  if (range.getRow() < 2) return;
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const actionColumn = headers.indexOf('Action') + 1;
  if (
    actionColumn <= 0 ||
    range.getColumn() > actionColumn ||
    range.getLastColumn() < actionColumn
  ) return;
  if (sheet.getName() === JOB_PIPELINE_SETUP.reviewQueue.sheet) {
    applyReviewQueueActionValidation_(sheet, range.getRow());
  } else if (sheet.getName() === JOB_PIPELINE_SETUP.appliedJobs.sheet) {
    applyAppliedJobsActionValidation_(sheet, range.getRow());
  }
}

function setupJobPipelineSheets() {
  const spreadsheet = SpreadsheetApp.getActiveSpreadsheet();
  const active = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.activeSheet, JOB_PIPELINE_SETUP.recordFields);
  const archive = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.archiveSheet, JOB_PIPELINE_SETUP.recordFields);
  const reviewQueue = ensureReviewQueueSheet_(
    spreadsheet,
    JOB_PIPELINE_SETUP.reviewQueue.sheet,
    JOB_PIPELINE_SETUP.reviewQueue.fields
  );
  const appliedJobs = ensureAppliedJobsSheet_(
    spreadsheet,
    JOB_PIPELINE_SETUP.appliedJobs.sheet,
    JOB_PIPELINE_SETUP.appliedJobs.fields
  );
  const claims = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.claimsSheet, JOB_PIPELINE_SETUP.claimFields);
  const dashboard = ensureSheet_(spreadsheet, JOB_PIPELINE_SETUP.dashboardSheet, JOB_PIPELINE_SETUP.dashboardFields);
  const analytics = ensureSheet_(
    spreadsheet,
    JOB_PIPELINE_SETUP.analyticsSheet,
    JOB_PIPELINE_SETUP.analyticsFields
  );
  const analyticsReports = ensureSheet_(
    spreadsheet,
    JOB_PIPELINE_SETUP.analyticsReportsSheet,
    JOB_PIPELINE_SETUP.analyticsReportFields
  );
  const recommendations = ensureSheet_(
    spreadsheet,
    JOB_PIPELINE_SETUP.recommendationsSheet,
    JOB_PIPELINE_SETUP.recommendationFields
  );
  const recommendationReports = ensureSheet_(
    spreadsheet,
    JOB_PIPELINE_SETUP.recommendationReportsSheet,
    JOB_PIPELINE_SETUP.recommendationReportFields
  );

  const versionMigration = [
    repairAndFormatVersionColumns_(active),
    repairAndFormatVersionColumns_(archive),
    repairAndFormatVersionColumns_(analytics),
    repairAndFormatVersionColumns_(analyticsReports),
    repairAndFormatVersionColumns_(recommendations),
    repairAndFormatVersionColumns_(recommendationReports)
  ];
  const unmappedVersionValues = versionMigration.flatMap(
    (result) => result.unmapped
  );
  if (unmappedVersionValues.length > 0) {
    throw new Error(
      'Unmapped non-text version values require manual review before workflow activation. ' +
      'Count: ' + unmappedVersionValues.length + '; ' +
      JSON.stringify(unmappedVersionValues.slice(0, 20))
    );
  }

  const processingClaimMigration =
    repairOrphanedProcessingClaims_(active);
  if (processingClaimMigration.counts.conflicting > 0) {
    throw new Error(
      'Confirmed orphan claim targets changed and require manual review before workflow activation. ' +
      JSON.stringify(processingClaimMigration.records.conflicting)
    );
  }
  const legacyMessageMigration = quarantineLegacyMessages_(active);
  const archivedLegacyMessageMigration =
    inspectArchivedLegacyMessageTargets_(archive);
  const activeLegacyMessageIds = [
    ...legacyMessageMigration.records.quarantined,
    ...legacyMessageMigration.records.already_quarantined,
    ...legacyMessageMigration.records.current_safe
  ].map((record) => record.canonical_job_id);
  const archivedLegacyMessageIds =
    archivedLegacyMessageMigration.records.archived.map(
      (record) => record.canonical_job_id
    );
  const activeLegacyMessageIdSet = new Set(activeLegacyMessageIds);
  const archivedLegacyMessageIdSet = new Set(archivedLegacyMessageIds);
  const overlappingLegacyMessageIds = activeLegacyMessageIds.filter(
    (identity) => archivedLegacyMessageIdSet.has(identity)
  );
  const coveredLegacyMessageIds = new Set([
    ...activeLegacyMessageIds,
    ...archivedLegacyMessageIds
  ]);
  const missingLegacyMessageIds =
    LEGACY_MESSAGE_QUARANTINE_IDS.filter(
      (identity) => !coveredLegacyMessageIds.has(identity)
    );
  if (
    legacyMessageMigration.counts.conflicting > 0 ||
    archivedLegacyMessageMigration.records.conflicting.length > 0 ||
    overlappingLegacyMessageIds.length > 0 ||
    missingLegacyMessageIds.length > 0 ||
    activeLegacyMessageIdSet.size !== activeLegacyMessageIds.length ||
    archivedLegacyMessageIdSet.size !== archivedLegacyMessageIds.length
  ) {
    throw new Error(
      'Confirmed legacy-message targets changed and require manual review before workflow activation. ' +
      JSON.stringify({
        counts: legacyMessageMigration.counts,
        conflicts: legacyMessageMigration.records.conflicting,
        archived: archivedLegacyMessageMigration,
        overlapping: overlappingLegacyMessageIds,
        missing: missingLegacyMessageIds
      })
    );
  }
  const applicationInputMigration = [
    repairLegacyApplyPointsInputs_(active),
    repairLegacyApplyPointsInputs_(archive)
  ];
  const conflictingApplicationInputs = applicationInputMigration.flatMap(
    (result) => result.records.conflicting
  );
  if (conflictingApplicationInputs.length > 0) {
    throw new Error(
      'Invalid legacy Apply Points inputs require manual review before workflow activation. ' +
      JSON.stringify(conflictingApplicationInputs.slice(0, 20))
    );
  }

  migrateLegacyCreatedAt_(active);
  migrateLegacyCreatedAt_(archive);
  migrateLegacyIdentityAndState_(active);
  migrateLegacyIdentityAndState_(archive);
  orderReviewColumns_(active);
  orderReviewColumns_(archive);
  applyReviewLayout_(active);
  applyReviewLayout_(archive);
  applyReviewQueueLayout_(reviewQueue);
  applyAppliedJobsLayout_(appliedJobs);
  formatInternalSheet_(claims);
  formatInternalSheet_(dashboard);
  formatInternalSheet_(analytics);
  formatInternalSheet_(analyticsReports);
  formatInternalSheet_(recommendations);
  formatInternalSheet_(recommendationReports);

  SpreadsheetApp.flush();
  const duplicateActiveIds = duplicateCanonicalIds_(active);
  const duplicateArchiveIds = duplicateCanonicalIds_(archive);
  if (duplicateActiveIds.length || duplicateArchiveIds.length) {
    throw new Error(
      'Canonical identity collisions require manual reconciliation before workflow activation. ' +
      'Sheet1: ' + duplicateActiveIds.join(', ') +
      '; Archive: ' + duplicateArchiveIds.join(', ')
    );
  }
  return {
    activeRows: active.getLastRow(),
    archiveRows: archive.getLastRow(),
    reviewQueueRows: reviewQueue.getLastRow(),
    appliedJobsRows: appliedJobs.getLastRow(),
    activeColumns: active.getLastColumn(),
    archiveColumns: archive.getLastColumn(),
    reviewQueueColumns: reviewQueue.getLastColumn(),
    appliedJobsColumns: appliedJobs.getLastColumn(),
    versionMigration,
    processingClaimMigration,
    legacyMessageMigration,
    archivedLegacyMessageMigration,
    applicationInputMigration
  };
}

function classifyVersionCell({
  field,
  value,
  displayValue,
  identity
}) {
  const confirmedProfileVersion = "2026-07-28";
  const confirmedProfileVersionSerial = 46231;
  if (value === "" || value === null || value === undefined) {
    return { status: "unchanged" };
  }
  if (typeof value === "string") {
    return { status: "unchanged" };
  }

  const rawType =
    value instanceof Date
      ? "date"
      : typeof value === "number"
        ? "number"
        : typeof value;
  const isConfirmedProfileVersion =
    field === "profile_version" &&
    Boolean(String(identity || "").trim()) &&
    String(displayValue || "").trim() === confirmedProfileVersion &&
    ((typeof value === "number" &&
      value === confirmedProfileVersionSerial) ||
      (value instanceof Date && Number.isFinite(value.getTime())));

  if (isConfirmedProfileVersion) {
    return {
      status: "repair",
      value: confirmedProfileVersion,
      raw_type: rawType
    };
  }

  return {
    status: "unmapped",
    raw_type: rawType
  };
}

function classifyOrphanedProcessingClaim({
  record,
  nowMs,
  leaseMs
}) {
  const confirmed = {
    "onlinejobs.ph:1663047": {
      token: "3634:onlinejobs.ph:1663047:evaluation",
      pipeline_status: "not_recommended"
    },
    "onlinejobs.ph:1696973": {
      token: "3634:onlinejobs.ph:1696973:evaluation",
      pipeline_status: "not_recommended"
    },
    "onlinejobs.ph:1696907": {
      token: "3634:onlinejobs.ph:1696907:evaluation",
      pipeline_status: "not_recommended"
    },
    "onlinejobs.ph:1615239": {
      token: "3634:onlinejobs.ph:1615239:evaluation",
      pipeline_status: "review_required"
    },
    "onlinejobs.ph:1697830": {
      token: "3634:onlinejobs.ph:1697830:evaluation",
      pipeline_status: "review_required"
    }
  };
  const identity = String(record?.canonical_job_id || "").trim();
  const token = String(record?.processing_token || "").trim();
  const stage = String(record?.processing_stage || "").trim();
  const startedAt = String(record?.processing_started_at || "").trim();
  const startedMs = Date.parse(startedAt);
  const currentMs = Number(nowMs);
  const lease = Number(leaseMs);

  if (!token) {
    return { status: "skipped", reason: "no_token" };
  }

  const hasUnexpiredActiveMetadata =
    Boolean(stage) &&
    Boolean(startedAt) &&
    Number.isFinite(startedMs) &&
    Number.isFinite(currentMs) &&
    Number.isFinite(lease) &&
    lease > 0 &&
    currentMs - startedMs < lease;
  if (hasUnexpiredActiveMetadata) {
    return { status: "preserved_active", reason: "unexpired_claim" };
  }

  const expected = confirmed[identity];
  if (!expected) {
    return { status: "skipped", reason: "unconfirmed_identity" };
  }
  if (
    token !== expected.token ||
    String(record?.pipeline_status || "").trim() !==
      expected.pipeline_status
  ) {
    return { status: "conflicting", reason: "target_state_changed" };
  }
  if (stage || startedAt) {
    return {
      status: "conflicting",
      reason: "target_has_processing_metadata"
    };
  }

  return { status: "clear", reason: "confirmed_orphan" };
}

function classifyLegacyMessageQuarantine(record, current) {
  const confirmedIdentities = new Set(LEGACY_MESSAGE_QUARANTINE_IDS);
  const identity = String(record?.canonical_job_id || "").trim();
  if (!confirmedIdentities.has(identity)) {
    return { status: "skipped", reason: "unconfirmed_identity" };
  }

  const decision = String(record?.application_decision || "").trim();
  const status = String(record?.pipeline_status || "").trim();
  const message = String(record?.generated_message || "");
  const profileVersion = String(
    record?.message_profile_version || ""
  ).trim();
  const validationStatus = String(
    record?.message_validation_status || ""
  ).trim();
  const alertStatus = String(record?.alert_status || "").trim();
  const alertSuppressedReason = String(
    record?.alert_suppressed_reason || ""
  ).trim();
  const category = String(record?.error_category || "").trim();
  const currentSafeMetadata =
    Boolean(message.trim()) &&
    !message.includes("johnlesterescarlan.netlify.app") &&
    profileVersion === current?.profile_version &&
    String(record?.message_policy_version || "").trim() ===
      current?.message_policy_version &&
    record?.message_validation_status === "valid" &&
    record?.application_pack_status === "ready" &&
    record?.application_pack_version === current?.pack_version &&
    record?.application_pack_profile_version ===
      current?.profile_version &&
    record?.application_pack_policy_version ===
      current?.pack_policy_version;
  if (currentSafeMetadata) {
    return { status: "current_safe", reason: "current_provenance" };
  }
  const alreadyQuarantined =
    !decision &&
    !message.trim() &&
    profileVersion === "legacy/unknown" &&
    validationStatus === "quarantined" &&
    alertStatus === "not_eligible" &&
    alertSuppressedReason
      .split(",")
      .map((reason) => reason.trim())
      .includes("message_quarantined") &&
    (
      category === "message_quarantined" ||
      [
        "recommended",
        "review_required",
        "generating",
        "retryable_error",
        "terminal_error"
      ].includes(status)
    );
  if (alreadyQuarantined) {
    return { status: "already_quarantined", reason: "unsafe_text_removed" };
  }
  if (decision || ["applied", "skipped", "archived"].includes(status)) {
    return { status: "conflicting", reason: "protected_record_changed" };
  }

  const hasReportedUnsafeEvidence =
    status === "ready" &&
    profileVersion === "legacy/unknown" &&
    message.includes(
      "https://johnlesterescarlan.netlify.app/john_lester_escarlan_resume.pdf"
    );
  if (hasReportedUnsafeEvidence) {
    return { status: "quarantine", reason: "confirmed_unsafe_legacy_message" };
  }

  return { status: "conflicting", reason: "target_state_changed" };
}

function inspectArchivedLegacyMessageTargets_(sheet) {
  const summary = {
    sheet: sheet.getName(),
    records: {
      archived: [],
      missing: [],
      conflicting: []
    }
  };
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const idColumn = headers.indexOf('canonical_job_id');
  const statusColumn = headers.indexOf('pipeline_status');
  if (idColumn < 0 || statusColumn < 0) {
    summary.records.conflicting.push({
      row_number: 1,
      canonical_job_id: '',
      reason: 'required_header_missing'
    });
    return summary;
  }

  const rowCount = Math.max(sheet.getLastRow() - 1, 0);
  const rows =
    rowCount > 0
      ? sheet.getRange(2, 1, rowCount, sheet.getLastColumn()).getValues()
      : [];
  LEGACY_MESSAGE_QUARANTINE_IDS.forEach((identity) => {
    const matches = [];
    rows.forEach((row, index) => {
      if (String(row[idColumn] || '').trim() === identity) {
        matches.push({
          row_number: index + 2,
          pipeline_status: String(row[statusColumn] || '').trim()
        });
      }
    });
    if (matches.length === 0) {
      summary.records.missing.push({
        canonical_job_id: identity
      });
      return;
    }
    if (matches.length > 1) {
      summary.records.conflicting.push({
        row_number: matches[0].row_number,
        canonical_job_id: identity,
        reason: 'duplicate_archive_records'
      });
      return;
    }
    if (matches[0].pipeline_status !== 'archived') {
      summary.records.conflicting.push({
        row_number: matches[0].row_number,
        canonical_job_id: identity,
        reason: 'unexpected_archive_status'
      });
      return;
    }
    summary.records.archived.push({
      row_number: matches[0].row_number,
      canonical_job_id: identity
    });
  });
  return summary;
}

function repairLegacyApplyPointsInputs_(sheet) {
  const summary = {
    sheet: sheet.getName(),
    counts: {
      cleared: 0,
      blank: 0,
      valid: 0,
      conflicting: 0
    },
    records: {
      cleared: [],
      conflicting: []
    }
  };
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const column = headers.indexOf('apply_points_input') + 1;
  if (column < 1) {
    summary.counts.conflicting += 1;
    summary.records.conflicting.push({
      row_number: 1,
      reason: 'required_header_missing'
    });
    return summary;
  }

  const rowCount = Math.max(sheet.getLastRow() - 1, 0);
  if (rowCount === 0) return summary;
  const values = sheet.getRange(2, column, rowCount, 1).getValues();
  const candidates = [];
  values.forEach((row, index) => {
    const value = row[0];
    if (value === '' || value === null || value === undefined) {
      summary.counts.blank += 1;
      return;
    }
    if (value === 0 || String(value).trim() === '0') {
      candidates.push(index + 2);
      return;
    }
    const numeric = Number(value);
    if (
      Number.isInteger(numeric) &&
      numeric >= JOB_PIPELINE_SETUP.reviewInputRules.applyPoints.minimum &&
      numeric <= JOB_PIPELINE_SETUP.reviewInputRules.applyPoints.maximum
    ) {
      summary.counts.valid += 1;
      return;
    }
    summary.counts.conflicting += 1;
    summary.records.conflicting.push({
      row_number: index + 2,
      value: String(value).slice(0, 64),
      reason: 'unsupported_legacy_value'
    });
  });
  if (summary.counts.conflicting > 0) return summary;

  candidates.forEach((rowNumber) => {
    const range = sheet.getRange(rowNumber, column);
    const current = range.getValue();
    if (!(current === 0 || String(current).trim() === '0')) {
      summary.counts.conflicting += 1;
      summary.records.conflicting.push({
        row_number: rowNumber,
        value: String(current).slice(0, 64),
        reason: 'target_changed_during_cleanup'
      });
      return;
    }
    range.setValue('');
    summary.counts.cleared += 1;
    if (summary.records.cleared.length < 20) {
      summary.records.cleared.push({
        row_number: rowNumber,
        reason: 'legacy_zero_sentinel'
      });
    }
  });
  return summary;
}

function repairAndFormatVersionColumns_(sheet) {
  const summary = {
    sheet: sheet.getName(),
    formatted: [],
    repaired: [],
    unmapped: []
  };
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const headerIndex = Object.fromEntries(
    headers.map((header, index) => [header, index])
  );
  const rowCount = Math.max(sheet.getLastRow() - 1, 0);
  const dataRowCount = Math.max(sheet.getMaxRows() - 1, 1);
  const rawRows =
    rowCount > 0
      ? sheet
          .getRange(2, 1, rowCount, sheet.getLastColumn())
          .getValues()
      : [];
  const displayRows =
    rowCount > 0
      ? sheet
          .getRange(2, 1, rowCount, sheet.getLastColumn())
          .getDisplayValues()
      : [];
  const identityFields = [
    'canonical_job_id',
    'analytics_row_id',
    'report_id',
    'recommendation_id',
    'run_id'
  ];
  const identityForRow = (row, displayRow) => {
    for (const field of identityFields) {
      const column = headerIndex[field];
      if (column === undefined) continue;
      const identity = String(row[column] || displayRow[column] || '').trim();
      if (identity) return identity;
    }
    return '';
  };
  const repairs = [];

  JOB_PIPELINE_SETUP.versionFields.forEach((field) => {
    const column = headerIndex[field];
    if (column === undefined) return;
    summary.formatted.push(field);

    rawRows.forEach((row, rowIndex) => {
      const result = classifyVersionCell({
        field,
        value: row[column],
        displayValue: displayRows[rowIndex][column],
        identity: identityForRow(row, displayRows[rowIndex])
      });
      if (result.status === 'repair') {
        repairs.push({
          row: rowIndex + 2,
          column: column + 1,
          field,
          identity: identityForRow(row, displayRows[rowIndex]),
          value: result.value,
          raw_type: result.raw_type
        });
      } else if (result.status === 'unmapped') {
        summary.unmapped.push({
          row_number: rowIndex + 2,
          field,
          identity: identityForRow(row, displayRows[rowIndex]),
          raw_type: result.raw_type,
          display_value: String(displayRows[rowIndex][column] || '').slice(0, 64)
        });
      }
    });

    sheet
      .getRange(2, column + 1, dataRowCount, 1)
      .setNumberFormat('@');
  });

  repairs.forEach((repair) => {
    sheet.getRange(repair.row, repair.column).setValue(repair.value);
    summary.repaired.push({
      row_number: repair.row,
      field: repair.field,
      identity: repair.identity,
      raw_type: repair.raw_type,
      value: repair.value
    });
  });
  return summary;
}

function repairOrphanedProcessingClaims_(sheet) {
  const summary = {
    sheet: sheet.getName(),
    counts: {
      cleared: 0,
      preserved_active: 0,
      skipped: 0,
      conflicting: 0
    },
    records: {
      cleared: [],
      preserved_active: [],
      skipped: [],
      conflicting: []
    }
  };
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const headerIndex = Object.fromEntries(
    headers.map((header, index) => [header, index])
  );
  const requiredFields = [
    'canonical_job_id',
    'pipeline_status',
    'processing_stage',
    'processing_token',
    'processing_started_at'
  ];
  if (requiredFields.some((field) => headerIndex[field] === undefined)) {
    summary.counts.conflicting += 1;
    summary.records.conflicting.push({
      row_number: 1,
      canonical_job_id: '',
      reason: 'required_header_missing'
    });
    return summary;
  }

  const rowCount = Math.max(sheet.getLastRow() - 1, 0);
  if (rowCount === 0) return summary;
  const rows = sheet
    .getRange(2, 1, rowCount, sheet.getLastColumn())
    .getValues();
  const recordFromRow = (row) =>
    Object.fromEntries(
      requiredFields.map((field) => [field, row[headerIndex[field]]])
    );
  const recordResult = (bucket, rowNumber, record, reason) => {
    summary.counts[bucket] += 1;
    if (summary.records[bucket].length < 20) {
      summary.records[bucket].push({
        row_number: rowNumber,
        canonical_job_id: String(record.canonical_job_id || '').slice(0, 128),
        reason
      });
    }
  };

  rows.forEach((row, index) => {
    const rowNumber = index + 2;
    const record = recordFromRow(row);
    const classification = classifyOrphanedProcessingClaim({
      record,
      nowMs: Date.now(),
      leaseMs: JOB_PIPELINE_SETUP.maximumClaimLeaseMs
    });
    if (classification.status !== 'clear') {
      recordResult(
        classification.status,
        rowNumber,
        record,
        classification.reason
      );
      return;
    }

    const currentRow = sheet
      .getRange(rowNumber, 1, 1, sheet.getLastColumn())
      .getValues()[0];
    const currentRecord = recordFromRow(currentRow);
    const rechecked = classifyOrphanedProcessingClaim({
      record: currentRecord,
      nowMs: Date.now(),
      leaseMs: JOB_PIPELINE_SETUP.maximumClaimLeaseMs
    });
    if (rechecked.status !== 'clear') {
      recordResult(
        'conflicting',
        rowNumber,
        currentRecord,
        'target_changed_during_cleanup'
      );
      return;
    }

    sheet
      .getRange(rowNumber, headerIndex.processing_token + 1)
      .setValue('');
    recordResult(
      'cleared',
      rowNumber,
      currentRecord,
      classification.reason
    );
  });
  return summary;
}

function quarantineLegacyMessages_(sheet) {
  const summary = {
    sheet: sheet.getName(),
    counts: {
      quarantined: 0,
      already_quarantined: 0,
      current_safe: 0,
      skipped: 0,
      conflicting: 0
    },
    records: {
      quarantined: [],
      already_quarantined: [],
      current_safe: [],
      skipped: [],
      conflicting: []
    }
  };
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const headerIndex = Object.fromEntries(
    headers.map((header, index) => [header, index])
  );
  const classificationFields = [
    'canonical_job_id',
    'pipeline_status',
    'application_decision',
    'generated_message',
    'message_profile_version',
    'message_policy_version',
    'message_validation_status',
    'alert_status',
    'alert_suppressed_reason',
    'application_pack_status',
    'application_pack_version',
    'application_pack_profile_version',
    'application_pack_policy_version',
    'error_category'
  ];
  if (
    classificationFields.some(
      (field) => headerIndex[field] === undefined
    )
  ) {
    summary.counts.conflicting += 1;
    summary.records.conflicting.push({
      row_number: 1,
      canonical_job_id: '',
      reason: 'required_header_missing'
    });
    return summary;
  }
  const rowCount = Math.max(sheet.getLastRow() - 1, 0);
  if (rowCount === 0) return summary;
  const rows = sheet
    .getRange(2, 1, rowCount, sheet.getLastColumn())
    .getValues();
  const recordFromRow = (row) =>
    Object.fromEntries(
      classificationFields.map(
        (field) => [field, row[headerIndex[field]]]
      )
    );
  const recordResult = (bucket, rowNumber, record, reason) => {
    summary.counts[bucket] += 1;
    if (summary.records[bucket].length < 20) {
      summary.records[bucket].push({
        row_number: rowNumber,
        canonical_job_id: String(
          record.canonical_job_id || ''
        ).slice(0, 128),
        reason
      });
    }
  };

  rows.forEach((row, index) => {
    const rowNumber = index + 2;
    const record = recordFromRow(row);
    const classification = classifyLegacyMessageQuarantine(
      record,
      JOB_PIPELINE_SETUP.currentMessageVersions
    );
    if (classification.status !== 'quarantine') {
      recordResult(
        classification.status,
        rowNumber,
        record,
        classification.reason
      );
      return;
    }

    const currentRow = sheet
      .getRange(rowNumber, 1, 1, sheet.getLastColumn())
      .getValues()[0];
    const currentRecord = recordFromRow(currentRow);
    const rechecked = classifyLegacyMessageQuarantine(
      currentRecord,
      JOB_PIPELINE_SETUP.currentMessageVersions
    );
    if (rechecked.status !== 'quarantine') {
      recordResult(
        'conflicting',
        rowNumber,
        currentRecord,
        'target_changed_during_quarantine'
      );
      return;
    }

    const nextRow = currentRow.slice();
    const now = new Date().toISOString();
    const updates = {
      pipeline_status: 'recommended',
      processing_stage: '',
      processing_commit_guard: '',
      processing_token: '',
      processing_started_at: '',
      attempt_count: 0,
      failed_stage: 'evaluation',
      next_retry_at: '',
      error_category: 'message_quarantined',
      error_summary:
        'Legacy application message was quarantined; re-evaluate and regenerate through current validation.',
      generated_message: '',
      message_policy_version: '',
      message_validation_status: 'quarantined',
      generated_at: '',
      application_instructions: '[]',
      screening_questions: '[]',
      selected_proof_refs: '[]',
      application_warnings: '[]',
      application_pack_status: '',
      application_pack_version: '',
      application_pack_profile_version: '',
      application_pack_policy_version: '',
      application_pack_generated_at: '',
      alert_status: 'not_eligible',
      alert_channel: '',
      alert_policy_version: '',
      alert_idempotency_key: '',
      alert_attempt_count: 0,
      alert_last_attempt_at: '',
      alert_next_retry_at: '',
      alert_sent_at: '',
      alert_provider_reference: '',
      alert_error_category: '',
      alert_error_summary: '',
      alert_suppressed_reason: 'message_quarantined',
      manual_action: '',
      updated_at: now
    };
    Object.entries(updates).forEach(([field, value]) => {
      nextRow[headerIndex[field]] = value;
    });
    nextRow[headerIndex.state_guard] = stateGuard_(
      nextRow[headerIndex.canonical_job_id],
      nextRow[headerIndex.pipeline_status],
      nextRow[headerIndex.application_decision],
      nextRow[headerIndex.first_reviewed_at],
      nextRow[headerIndex.apply_points_used],
      nextRow[headerIndex.application_message_strategy],
      nextRow[headerIndex.outcome],
      nextRow[headerIndex.outcome_events]
    );
    sheet
      .getRange(rowNumber, 1, 1, sheet.getLastColumn())
      .setValues([nextRow]);
    recordResult(
      'quarantined',
      rowNumber,
      currentRecord,
      classification.reason
    );
  });
  return summary;
}

function duplicateCanonicalIds_(sheet) {
  if (sheet.getLastRow() < 2) return [];
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const idColumn = headers.indexOf('canonical_job_id') + 1;
  if (idColumn < 1) return [];
  const values = sheet
    .getRange(2, idColumn, sheet.getLastRow() - 1, 1)
    .getDisplayValues()
    .flat()
    .filter(Boolean);
  const seen = new Set();
  const duplicates = new Set();
  values.forEach((value) => {
    if (seen.has(value)) duplicates.add(value);
    seen.add(value);
  });
  return [...duplicates];
}

function ensureSheet_(spreadsheet, name, requiredHeaders) {
  const sheet = spreadsheet.getSheetByName(name) || spreadsheet.insertSheet(name);
  const existingWidth = Math.max(sheet.getLastColumn(), 1);
  const existing = sheet.getRange(1, 1, 1, existingWidth).getDisplayValues()[0];
  const headers = existing.every((value) => !value) ? [] : existing;
  const missing = requiredHeaders.filter((header) => !headers.includes(header));
  const merged = headers.concat(missing);
  if (merged.length > 0) {
    sheet.getRange(1, 1, 1, merged.length).setValues([merged]);
  }
  sheet.setFrozenRows(1);
  return sheet;
}

function ensureReviewQueueSheet_(spreadsheet, name, requiredHeaders) {
  return ensureControlledProjectionSheet_(
    spreadsheet,
    name,
    requiredHeaders,
    'Review Queue'
  );
}

function ensureAppliedJobsSheet_(spreadsheet, name, requiredHeaders) {
  return ensureControlledProjectionSheet_(
    spreadsheet,
    name,
    requiredHeaders,
    'Applied Jobs'
  );
}

function ensureControlledProjectionSheet_(
  spreadsheet,
  name,
  requiredHeaders,
  displayName
) {
  const sheet = spreadsheet.getSheetByName(name) || spreadsheet.insertSheet(name);
  const existingWidth = Math.max(sheet.getLastColumn(), 1);
  const rawHeaders = sheet
    .getRange(1, 1, 1, existingWidth)
    .getDisplayValues()[0]
    .map((value) => String(value || '').trim());
  const existingData =
    sheet.getLastRow() > 1
      ? sheet
          .getRange(2, 1, sheet.getLastRow() - 1, existingWidth)
          .getDisplayValues()
      : [];
  const headerlessDataColumns = rawHeaders
    .map((header, index) =>
      !header &&
      existingData.some((row) => String(row[index] || '').trim())
        ? index
        : -1
    )
    .filter((index) => index >= 0);
  if (headerlessDataColumns.length > 0) {
    throw new Error(
      displayName +
        ' contains data under blank headers and requires manual reconciliation at column(s): ' +
        headerlessDataColumns
          .map((index) => columnLetter_(index + 1))
          .join(', ')
    );
  }
  let lastHeaderIndex = -1;
  rawHeaders.forEach((header, index) => {
    if (header) lastHeaderIndex = index;
  });
  const existing =
    lastHeaderIndex < 0 ? [] : rawHeaders.slice(0, lastHeaderIndex + 1);
  const blankHeaderIndexes = existing
    .map((header, index) => (header ? -1 : index))
    .filter((index) => index >= 0);
  if (blankHeaderIndexes.length > 0) {
    throw new Error(
      displayName +
        ' contains blank header gaps and requires manual reconciliation at column(s): ' +
        blankHeaderIndexes.map((index) => columnLetter_(index + 1)).join(', ')
    );
  }
  if (existing.length === 0 && sheet.getLastRow() > 1) {
    throw new Error(
      displayName +
        ' contains data without headers and requires manual reconciliation'
    );
  }
  const unsupported = existing.filter((header) => !requiredHeaders.includes(header));
  if (unsupported.length > 0) {
    throw new Error(
      displayName + ' contains unsupported headers and requires manual reconciliation: ' +
      unsupported.join(', ')
    );
  }
  const duplicates = existing.filter(
    (header, index) => existing.indexOf(header) !== index
  );
  if (duplicates.length > 0) {
    throw new Error(
      displayName + ' contains duplicate headers and requires manual reconciliation: ' +
      [...new Set(duplicates)].join(', ')
    );
  }
  const merged = existing.concat(
    requiredHeaders.filter((header) => !existing.includes(header))
  );
  if (merged.length > 0) {
    sheet.getRange(1, 1, 1, merged.length).setValues([merged]);
  }
  const headers = sheet
    .getRange(1, 1, 1, Math.max(sheet.getLastColumn(), 1))
    .getDisplayValues()[0];
  let destination = 1;
  requiredHeaders.forEach((header) => {
    const currentIndex = headers.indexOf(header);
    if (currentIndex < 0) return;
    if (currentIndex + 1 !== destination) {
      sheet.moveColumns(
        sheet.getRange(1, currentIndex + 1, sheet.getMaxRows(), 1),
        destination
      );
      const [moved] = headers.splice(currentIndex, 1);
      headers.splice(destination - 1, 0, moved);
    }
    destination += 1;
  });
  sheet.setFrozenRows(1);
  return sheet;
}

function migrateLegacyCreatedAt_(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const legacyIndex = headers.indexOf('created_at ');
  const canonicalIndex = headers.indexOf('created_at');
  if (legacyIndex < 0 || canonicalIndex < 0 || sheet.getLastRow() < 2) return;

  const rowCount = sheet.getLastRow() - 1;
  const legacy = sheet.getRange(2, legacyIndex + 1, rowCount, 1).getValues();
  const canonicalRange = sheet.getRange(2, canonicalIndex + 1, rowCount, 1);
  const canonical = canonicalRange.getValues();
  const merged = canonical.map((row, index) => [row[0] || legacy[index][0] || '']);
  canonicalRange.setValues(merged);
}

function migrateLegacyIdentityAndState_(sheet) {
  if (sheet.getLastRow() < 2) return;
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const headerIndex = Object.fromEntries(headers.map((header, index) => [header, index]));
  const rows = sheet
    .getRange(2, 1, sheet.getLastRow() - 1, sheet.getLastColumn())
    .getValues();
  const targets = [
    'source',
    'source_job_id',
    'canonical_job_id',
    'canonical_url',
    'pipeline_status',
    'application_decision',
    'first_reviewed_at',
    'apply_points_used',
    'application_message_strategy',
    'archived_from_status',
    'profile_version',
    'message_profile_version',
    'outcome_events',
    'state_guard'
  ];
  const output = Object.fromEntries(targets.map((target) => [target, []]));
  const value = (row, header) =>
    headerIndex[header] === undefined ? '' : row[headerIndex[header]];

  rows.forEach((row) => {
    const hasJob = [
      'canonical_job_id',
      'canonical_url',
      'job_url',
      'source_job_id',
      'job_title'
    ].some((header) => String(value(row, header) || '').trim());
    const current = Object.fromEntries(targets.map((target) => [target, value(row, target)]));
    if (!hasJob) {
      targets.forEach((target) => output[target].push([current[target]]));
      return;
    }

    const source = String(current.source || 'onlinejobs.ph').trim().toLowerCase();
    const canonicalUrl =
      String(current.canonical_url || '').trim() ||
      normalizeLegacyUrl_(value(row, 'job_url'));
    const sourceJobId =
      String(current.source_job_id || '').trim() ||
      (canonicalUrl.match(/\/jobseekers\/job\/[^/]*?(\d+)$/i) || [])[1] ||
      '';
    const canonicalJobId =
      String(current.canonical_job_id || '').trim() ||
      (sourceJobId
        ? source + ':' + sourceJobId
        : canonicalUrl
          ? source + ':url:' + fnv32_(canonicalUrl)
          : '');
    const legacyStatus = String(value(row, 'status') || '').trim().toLowerCase();
    const mappedLegacyStatus =
      JOB_PIPELINE_SETUP.legacyStatusMapping[legacyStatus] || legacyStatus || 'discovered';
    let pipelineStatus = String(current.pipeline_status || '').trim() || mappedLegacyStatus;
    let archivedFromStatus = String(current.archived_from_status || '').trim();
    if (
      sheet.getName() === JOB_PIPELINE_SETUP.archiveSheet &&
      !String(current.pipeline_status || '').trim()
    ) {
      archivedFromStatus = archivedFromStatus || mappedLegacyStatus;
      pipelineStatus = 'archived';
    }
    const applicationDecision =
      String(current.application_decision || '').trim() ||
      (archivedFromStatus === 'applied' || pipelineStatus === 'applied'
        ? 'applied'
        : archivedFromStatus === 'skipped' || pipelineStatus === 'skipped'
          ? 'skipped'
          : '');
    const outcome = String(value(row, 'outcome') || '').trim();
    const firstReviewedAt = String(current.first_reviewed_at || '').trim();
    const applyPointsUsed = String(current.apply_points_used || '').trim();
    const applicationMessageStrategy =
      String(current.application_message_strategy || '').trim();
    const outcomeEvents = String(current.outcome_events || '').trim();
    const generatedMessage = String(value(row, 'generated_message') || '');
    const profileVersion = String(current.profile_version || '').trim() || 'legacy/unknown';
    const messageProfileVersion =
      String(current.message_profile_version || '').trim() ||
      (generatedMessage ? 'legacy/unknown' : '');
    const stateGuard = canonicalJobId
      ? stateGuard_(
          canonicalJobId,
          pipelineStatus,
          applicationDecision,
          firstReviewedAt,
          applyPointsUsed,
          applicationMessageStrategy,
          outcome,
          outcomeEvents
        )
      : '';
    const migrated = {
      source,
      source_job_id: sourceJobId,
      canonical_job_id: canonicalJobId,
      canonical_url: canonicalUrl,
      pipeline_status: pipelineStatus,
      application_decision: applicationDecision,
      first_reviewed_at: firstReviewedAt,
      apply_points_used: applyPointsUsed,
      application_message_strategy: applicationMessageStrategy,
      archived_from_status: archivedFromStatus,
      profile_version: profileVersion,
      message_profile_version: messageProfileVersion,
      outcome_events: outcomeEvents,
      state_guard: stateGuard
    };
    targets.forEach((target) => output[target].push([migrated[target]]));
  });

  targets.forEach((target) => {
    const column = headerIndex[target];
    if (column !== undefined) {
      sheet.getRange(2, column + 1, rows.length, 1).setValues(output[target]);
    }
  });
}

function normalizeLegacyUrl_(value) {
  let url = String(value || '').trim();
  if (!url) return '';
  if (url.startsWith('/')) url = 'https://onlinejobs.ph' + url;
  url = url
    .replace(/^http:\/\//i, 'https://')
    .replace(/^https:\/\/www\.onlinejobs\.ph/i, 'https://onlinejobs.ph')
    .split(/[?#]/)[0]
    .replace(/\/+$/, '');
  return /^https:\/\/onlinejobs\.ph\/jobseekers\/job\//i.test(url) ? url : '';
}

function stateGuard_(
  canonicalJobId,
  pipelineStatus,
  applicationDecision,
  firstReviewedAt,
  applyPointsUsed,
  applicationMessageStrategy,
  outcome,
  outcomeEvents
) {
  return (
    canonicalJobId +
    '|' +
    fnv32_(
      [
        canonicalJobId,
        pipelineStatus,
        applicationDecision,
        firstReviewedAt,
        applyPointsUsed,
        applicationMessageStrategy,
        outcome,
        outcomeEvents || '[]'
      ].join(
        String.fromCharCode(31)
      )
    )
  );
}

function fnv32_(value) {
  let hash = 2166136261;
  String(value).split('').forEach((character) => {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  });
  return (hash >>> 0).toString(16).padStart(8, '0');
}

function orderReviewColumns_(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  let destination = 1;
  JOB_PIPELINE_SETUP.reviewColumns.forEach((header) => {
    const currentIndex = headers.indexOf(header);
    if (currentIndex < 0) return;
    if (currentIndex + 1 !== destination) {
      sheet.moveColumns(
        sheet.getRange(1, currentIndex + 1, sheet.getMaxRows(), 1),
        destination
      );
      const [moved] = headers.splice(currentIndex, 1);
      headers.splice(destination - 1, 0, moved);
    }
    destination += 1;
  });
}

function applyReviewLayout_(sheet) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
  const actionColumn = headers.indexOf('manual_action') + 1;
  if (actionColumn > 0) {
    const validation = SpreadsheetApp.newDataValidation()
      .requireValueInList(JOB_PIPELINE_SETUP.manualActions, true)
      .setAllowInvalid(false)
      .setHelpText('Choose a supported Job Pipeline action. The reviewer workflow validates the state transition.')
      .build();
    sheet.getRange(2, actionColumn, Math.max(sheet.getMaxRows() - 1, 1), 1).setDataValidation(validation);
  }

  const applyPointsColumn = headers.indexOf('apply_points_input') + 1;
  if (applyPointsColumn > 0) {
    const rule = JOB_PIPELINE_SETUP.reviewInputRules.applyPoints;
    const column = columnLetter_(applyPointsColumn);
    const validation = SpreadsheetApp.newDataValidation()
      .requireFormulaSatisfied(
        '=OR($' + column + '2="",AND(ISNUMBER($' + column +
        '2),$' + column + '2=INT($' + column + '2),$' + column +
        '2>=' + rule.minimum + ',$' + column + '2<=' + rule.maximum + '))'
      )
      .setAllowInvalid(false)
      .setHelpText(
        'Optional actual Apply Points. Enter a whole number from ' +
        rule.minimum + ' to ' + rule.maximum + ', or leave blank when unknown.'
      )
      .build();
    sheet
      .getRange(2, applyPointsColumn, Math.max(sheet.getMaxRows() - 1, 1), 1)
      .setDataValidation(validation);
  }

  const strategyColumn =
    headers.indexOf('application_message_strategy_input') + 1;
  if (strategyColumn > 0) {
    const pattern = String(
      JOB_PIPELINE_SETUP.reviewInputRules.messageStrategy.pattern
    ).replace(/"/g, '""');
    const column = columnLetter_(strategyColumn);
    const validation = SpreadsheetApp.newDataValidation()
      .requireFormulaSatisfied(
        '=OR($' + column + '2="",REGEXMATCH(TO_TEXT($' +
        column + '2),"' + pattern + '"))'
      )
      .setAllowInvalid(false)
      .setHelpText(
        'Optional versioned strategy identifier, for example instruction-aware/v1.'
      )
      .build();
    sheet
      .getRange(2, strategyColumn, Math.max(sheet.getMaxRows() - 1, 1), 1)
      .setDataValidation(validation);
  }

  const statusColumn = headers.indexOf('pipeline_status') + 1;
  if (statusColumn > 0) {
    const range = sheet.getRange(2, statusColumn, Math.max(sheet.getMaxRows() - 1, 1), 1);
    const rules = [
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="ready"', '#d9ead3'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="recommended"', '#cfe2f3'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="review_required"', '#fff2cc'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="retryable_error"', '#f4cccc'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="unavailable"', '#d9d9d9')
    ];
    const unrelatedRules = sheet.getConditionalFormatRules().filter((rule) =>
      rule.getRanges().every(
        (ruleRange) =>
          ruleRange.getSheet().getSheetId() !== sheet.getSheetId() ||
          statusColumn < ruleRange.getColumn() ||
          statusColumn > ruleRange.getLastColumn()
      )
    );
    sheet.setConditionalFormatRules(unrelatedRules.concat(rules));
  }

  const messageColumn = headers.indexOf('generated_message') + 1;
  if (messageColumn > 0) {
    sheet.setColumnWidth(messageColumn, 420);
    sheet.getRange(2, messageColumn, Math.max(sheet.getMaxRows() - 1, 1), 1).setWrap(true);
  }
  const titleColumn = headers.indexOf('job_title') + 1;
  if (titleColumn > 0) sheet.setColumnWidth(titleColumn, 260);
  const urlColumn = headers.indexOf('canonical_url') + 1;
  if (urlColumn > 0) sheet.setColumnWidth(urlColumn, 260);
  [
    'match_reasons',
    'requirement_gaps',
    'requirement_gap_details',
    'ranking_factors',
    'ranking_missing_signals',
    'application_instructions',
    'screening_questions',
    'selected_proof_refs',
    'application_warnings',
    'notes'
  ].forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) {
      sheet.setColumnWidth(column, 280);
      sheet.getRange(2, column, Math.max(sheet.getMaxRows() - 1, 1), 1).setWrap(true);
    }
  });
  JOB_PIPELINE_SETUP.hiddenColumns.forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) sheet.hideColumns(column);
  });
  sheet.setFrozenColumns(Math.min(3, sheet.getLastColumn()));
  sheet.getRange(1, 1, 1, sheet.getLastColumn()).setFontWeight('bold').setBackground('#1f4e78').setFontColor('#ffffff');

  removeGeneratedProtections_(sheet);
  headers.forEach((header, index) => {
    if (!JOB_PIPELINE_SETUP.editableColumns.includes(header)) {
      const protection = sheet
        .getRange(2, index + 1, Math.max(sheet.getMaxRows() - 1, 1), 1)
        .protect()
        .setDescription('Job Pipeline generated field: ' + header);
      protection.setWarningOnly(true);
    }
  });
}

function applyReviewQueueLayout_(sheet) {
  const queue = JOB_PIPELINE_SETUP.reviewQueue;
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const dataRows = Math.max(sheet.getMaxRows() - 1, 1);
  const actionColumn = headers.indexOf('Action') + 1;
  if (actionColumn > 0) {
    applyReviewQueueActionValidation_(sheet);
    sheet.setColumnWidth(actionColumn, 190);
  }

  const statusColumn = headers.indexOf('Status') + 1;
  if (statusColumn > 0) {
    const range = sheet.getRange(2, statusColumn, dataRows, 1);
    const rules = [
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="ready"', '#d9ead3'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="recommended"', '#cfe2f3'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="review_required"', '#fff2cc'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="retryable_error"', '#fce5cd'),
      conditionalRule_(range, '=$' + columnLetter_(statusColumn) + '2="terminal_error"', '#f4cccc')
    ];
    const unrelatedRules = sheet.getConditionalFormatRules().filter((rule) =>
      rule.getRanges().every(
        (ruleRange) =>
          ruleRange.getSheet().getSheetId() !== sheet.getSheetId() ||
          statusColumn < ruleRange.getColumn() ||
          statusColumn > ruleRange.getLastColumn()
      )
    );
    sheet.setConditionalFormatRules(unrelatedRules.concat(rules));
    sheet.setColumnWidth(statusColumn, 150);
  }

  const widths = {
    'Job title': 260,
    Company: 190,
    Score: 90,
    'Reason for review': 360,
    'Generated message': 420,
    'Job link': 260
  };
  Object.entries(widths).forEach(([header, width]) => {
    const column = headers.indexOf(header) + 1;
    if (column <= 0) return;
    sheet.setColumnWidth(column, width);
    if (['Reason for review', 'Generated message'].includes(header)) {
      sheet.getRange(2, column, dataRows, 1).setWrap(true);
    }
  });

  queue.visible_columns.forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) sheet.showColumns(column);
  });
  queue.hidden_columns.forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) sheet.hideColumns(column);
  });
  sheet.setFrozenColumns(2);
  sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .setFontWeight('bold')
    .setBackground('#1f4e78')
    .setFontColor('#ffffff');

  removeGeneratedProtections_(sheet);
  headers.forEach((header, index) => {
    if (header === 'Action') return;
    const protection = sheet
      .getRange(2, index + 1, dataRows, 1)
      .protect()
      .setDescription('Job Pipeline Review Queue generated field: ' + header);
    protection.setWarningOnly(true);
  });
}

function applyReviewQueueActionValidation_(sheet, selectedRow) {
  const queue = JOB_PIPELINE_SETUP.reviewQueue;
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const actionColumn = headers.indexOf('Action') + 1;
  const statusColumn = headers.indexOf('Status') + 1;
  if (actionColumn <= 0 || statusColumn <= 0) return;
  const firstRow = Math.max(Number(selectedRow) || 2, 2);
  const rowCount = selectedRow
    ? 1
    : Math.max(sheet.getMaxRows() - 1, 1);
  const statuses = sheet
    .getRange(firstRow, statusColumn, rowCount, 1)
    .getDisplayValues();
  const recoveryStatuses = new Set(
    queue.generation_recovery.statuses
  );
  const recoveryValidation = SpreadsheetApp.newDataValidation()
    .requireValueInList(['', 'Generate Application', 'Skip'], true)
    .setAllowInvalid(false)
    .setHelpText(
      'Retry generation or skip this job. I Applied is unavailable until a validated message is ready.'
    )
    .build();
  const defaultValidation = SpreadsheetApp.newDataValidation()
    .requireValueInList([''].concat(Object.keys(queue.actions)), true)
    .setAllowInvalid(false)
    .setHelpText(
      'Choose Generate Application, I Applied, or Skip. The Reviewer revalidates Sheet1 before applying the action.'
    )
    .build();
  const validations = statuses.map((values) => [
    recoveryStatuses.has(String(values[0] || '').trim())
      ? recoveryValidation
      : defaultValidation
  ]);
  sheet
    .getRange(firstRow, actionColumn, rowCount, 1)
    .setDataValidations(validations);
}

function applyAppliedJobsLayout_(sheet) {
  const appliedJobs = JOB_PIPELINE_SETUP.appliedJobs;
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const dataRows = Math.max(sheet.getMaxRows() - 1, 1);
  const widths = {
    'Applied at': 170,
    'Job title': 260,
    Company: 190,
    'Generated message': 420,
    'Job link': 260,
    'Current outcome': 150,
    'Outcome updated at': 170,
    Action: 180
  };
  Object.entries(widths).forEach(([header, width]) => {
    const column = headers.indexOf(header) + 1;
    if (column <= 0) return;
    sheet.setColumnWidth(column, width);
    if (header === 'Generated message') {
      sheet.getRange(2, column, dataRows, 1).setWrap(true);
    }
  });

  const actionColumn = headers.indexOf('Action') + 1;
  if (actionColumn > 0) applyAppliedJobsActionValidation_(sheet);
  appliedJobs.visible_columns.forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) sheet.showColumns(column);
  });
  appliedJobs.hidden_columns.forEach((header) => {
    const column = headers.indexOf(header) + 1;
    if (column > 0) sheet.hideColumns(column);
  });
  sheet.setFrozenColumns(2);
  sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .setFontWeight('bold')
    .setBackground('#1f4e78')
    .setFontColor('#ffffff');

  removeGeneratedProtections_(sheet);
  headers.forEach((header, index) => {
    if (header === 'Action') return;
    const protection = sheet
      .getRange(2, index + 1, dataRows, 1)
      .protect()
      .setDescription('Job Pipeline Applied Jobs generated field: ' + header);
    protection.setWarningOnly(true);
  });
}

function applyAppliedJobsActionValidation_(sheet, selectedRow) {
  const headers = sheet
    .getRange(1, 1, 1, sheet.getLastColumn())
    .getDisplayValues()[0];
  const actionColumn = headers.indexOf('Action') + 1;
  if (actionColumn <= 0) return;
  const firstRow = Math.max(Number(selectedRow) || 2, 2);
  const rowCount = selectedRow
    ? 1
    : Math.max(sheet.getMaxRows() - 1, 1);
  const validation = SpreadsheetApp.newDataValidation()
    .requireValueInList(
      [''].concat(Object.keys(JOB_PIPELINE_SETUP.appliedJobs.actions)),
      true
    )
    .setAllowInvalid(false)
    .setHelpText(
      'Record a follow-up outcome. The Reviewer revalidates the authoritative applied record before updating it.'
    )
    .build();
  sheet
    .getRange(firstRow, actionColumn, rowCount, 1)
    .setDataValidation(validation);
}

function formatInternalSheet_(sheet) {
  sheet.getRange(1, 1, 1, sheet.getLastColumn()).setFontWeight('bold').setBackground('#666666').setFontColor('#ffffff');
  sheet.autoResizeColumns(1, sheet.getLastColumn());
}

function removeGeneratedProtections_(sheet) {
  sheet.getProtections(SpreadsheetApp.ProtectionType.RANGE).forEach((protection) => {
    const description = protection.getDescription() || '';
    if (
      description.startsWith('Job Pipeline generated field:') ||
      description.startsWith('Job Pipeline Review Queue generated field:') ||
      description.startsWith('Job Pipeline Applied Jobs generated field:')
    ) {
      protection.remove();
    }
  });
}

function conditionalRule_(range, formula, color) {
  return SpreadsheetApp.newConditionalFormatRule()
    .whenFormulaSatisfied(formula)
    .setBackground(color)
    .setRanges([range])
    .build();
}

function sortPriorityQueue() {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(JOB_PIPELINE_SETUP.activeSheet);
  if (!sheet || sheet.getLastRow() < 3) return;
  const lock = LockService.getDocumentLock();
  if (!lock.tryLock(5000)) throw new Error('Priority queue is busy; retry the sort.');
  try {
    const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getDisplayValues()[0];
    const index = Object.fromEntries(headers.map((header, position) => [header, position]));
    for (const required of [
      'pipeline_status',
      'opportunity_score',
      'match_score',
      'ranking_confidence',
      'posted_at',
      'created_at',
      'canonical_job_id'
    ]) {
      if (index[required] === undefined) throw new Error(required + ' column is required');
    }
    const range = sheet.getRange(2, 1, sheet.getLastRow() - 1, sheet.getLastColumn());
    const rows = range.getValues();
    const statusPriority = {
      ready: 4,
      recommended: 3,
      review_required: 2,
      retryable_error: 1
    };
    const confidencePriority = { high: 3, medium: 2, low: 1 };
    const rankingValue = (row) => {
      const opportunity = row[index.opportunity_score];
      if (String(opportunity ?? '').trim() !== '' && Number.isFinite(Number(opportunity))) {
        return Number(opportunity);
      }
      const legacy = row[index.match_score];
      return String(legacy ?? '').trim() !== '' && Number.isFinite(Number(legacy))
        ? Number(legacy)
        : 0;
    };
    const timestamp = (value) => {
      const parsed = value instanceof Date ? value.getTime() : Date.parse(String(value || ''));
      return Number.isFinite(parsed) ? parsed : Number.NEGATIVE_INFINITY;
    };
    rows.sort((left, right) => {
      const status =
        (statusPriority[String(right[index.pipeline_status])] || 0) -
        (statusPriority[String(left[index.pipeline_status])] || 0);
      if (status !== 0) return status;
      const score = rankingValue(right) - rankingValue(left);
      if (score !== 0) return score;
      const confidence =
        (confidencePriority[String(right[index.ranking_confidence])] || 0) -
        (confidencePriority[String(left[index.ranking_confidence])] || 0);
      if (confidence !== 0) return confidence;
      const rightPosted = timestamp(right[index.posted_at]);
      const leftPosted = timestamp(left[index.posted_at]);
      if (rightPosted !== leftPosted) return rightPosted > leftPosted ? 1 : -1;
      const rightCreated = timestamp(right[index.created_at]);
      const leftCreated = timestamp(left[index.created_at]);
      if (rightCreated !== leftCreated) return rightCreated > leftCreated ? 1 : -1;
      return String(left[index.canonical_job_id] || '').localeCompare(
        String(right[index.canonical_job_id] || '')
      );
    });
    range.setValues(rows);
  } finally {
    lock.releaseLock();
  }
}

function columnLetter_(column) {
  let value = column;
  let result = '';
  while (value > 0) {
    const remainder = (value - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    value = Math.floor((value - 1) / 26);
  }
  return result;
}
