// Generated by scripts/build-sheet-setup.mjs. Do not edit directly.
// This provisions a fresh workbook only. It never reads another workbook or imports old rows.
const JOB_PIPELINE_SETUP = {
  "timezone": "Asia/Manila",
  "sheets": {
    "review_queue": {
      "name": "Review Queue",
      "visible": true,
      "authoritative_for": "active",
      "visible_columns": [
        "pipeline_status",
        "user_action",
        "job_title",
        "company",
        "opportunity_score",
        "decision_reason",
        "required_input",
        "generated_message",
        "canonical_url",
        "posted_at",
        "matched_keywords",
        "error_summary",
        "notes"
      ]
    },
    "applied_jobs": {
      "name": "Applied Jobs",
      "visible": true,
      "authoritative_for": "applied",
      "visible_columns": [
        "applied_at",
        "job_title",
        "company",
        "generated_message",
        "canonical_url",
        "outcome",
        "outcome_at",
        "notes"
      ]
    },
    "archive": {
      "name": "Archive",
      "visible": true,
      "authoritative_for": "archived",
      "visible_columns": [
        "archived_at",
        "archive_reason",
        "job_title",
        "company",
        "decision_reason",
        "canonical_url",
        "notes"
      ]
    },
    "system": {
      "name": "_System",
      "visible": false,
      "authoritative_for": "short_lived_claims",
      "fields": [
        "claim_key",
        "canonical_job_id",
        "stage",
        "token",
        "created_at",
        "expires_at"
      ]
    }
  },
  "recordFields": [
    "source",
    "source_job_id",
    "canonical_job_id",
    "record_version",
    "state_guard",
    "canonical_url",
    "job_title",
    "company",
    "job_description",
    "salary_text",
    "posted_at",
    "discovered_at",
    "last_seen_at",
    "matched_keywords",
    "source_availability",
    "pipeline_status",
    "user_action",
    "decision_reason",
    "required_input",
    "review_approved_at",
    "review_approval_note",
    "qualification_score",
    "opportunity_score",
    "ranking_confidence",
    "match_reasons",
    "requirement_gaps",
    "profile_version",
    "policy_version",
    "evaluated_at",
    "processing_stage",
    "processing_token",
    "processing_started_at",
    "attempt_count",
    "next_retry_at",
    "error_category",
    "error_summary",
    "generated_message",
    "message_validation_status",
    "message_profile_version",
    "message_policy_version",
    "generated_at",
    "application_instructions",
    "screening_questions",
    "selected_proof_refs",
    "application_warnings",
    "application_pack_status",
    "application_pack_version",
    "application_pack_profile_version",
    "application_pack_policy_version",
    "application_pack_generated_at",
    "alert_status",
    "alert_idempotency_key",
    "alert_claim_token",
    "alert_attempt_count",
    "alert_last_attempt_at",
    "alert_next_retry_at",
    "alert_sent_at",
    "alert_provider_reference",
    "alert_error_category",
    "alert_error_summary",
    "applied_at",
    "archived_at",
    "archive_reason",
    "outcome",
    "outcome_recorded_value",
    "outcome_at",
    "notes",
    "created_at",
    "updated_at"
  ],
  "editableColumns": {
    "Review Queue": [
      "user_action",
      "notes"
    ],
    "Applied Jobs": [
      "outcome",
      "notes"
    ],
    "Archive": [
      "notes"
    ]
  },
  "actionValidation": {
    "ready_to_apply": [
      "",
      "I Applied",
      "Skip"
    ],
    "review_needed": [
      "",
      "Approve",
      "Deny"
    ],
    "default": [
      ""
    ]
  },
  "outcomeValidation": [
    "",
    "no_response",
    "replied",
    "interview",
    "offer",
    "rejected"
  ],
  "forbiddenLegacySheets": [
    "Sheet1",
    "Dashboard",
    "Analytics",
    "AnalyticsReports",
    "Recommendations",
    "RecommendationReports",
    "ProcessingClaims"
  ],
  "maximumRows": 2000
};

function setupFreshJobPipeline() {
  const workbook = SpreadsheetApp.getActive();
  workbook.setSpreadsheetTimeZone(JOB_PIPELINE_SETUP.timezone);
  const lock = LockService.getDocumentLock();
  lock.waitLock(30000);
  try {
    const expected = [
      JOB_PIPELINE_SETUP.sheets.review_queue.name,
      JOB_PIPELINE_SETUP.sheets.applied_jobs.name,
      JOB_PIPELINE_SETUP.sheets.archive.name,
      JOB_PIPELINE_SETUP.sheets.system.name
    ];

    // Create the intended tabs before removing an empty default Sheet1.
    expected.forEach((name) => {
      if (!workbook.getSheetByName(name)) workbook.insertSheet(name);
    });

    workbook.getSheets().forEach((sheet) => {
      if (expected.includes(sheet.getName())) return;
      if (sheet.getLastRow() > 1 || sheet.getLastColumn() > 1 ||
          String(sheet.getRange(1, 1).getValue() || '').trim() !== '') {
        throw new Error(
          'Fresh setup refused to delete non-empty unexpected sheet: ' +
          sanitizeSetupDiagnostic_(sheet.getName())
        );
      }
      workbook.deleteSheet(sheet);
    });

    configureRecordSheet_(
      workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.review_queue.name),
      JOB_PIPELINE_SETUP.sheets.review_queue.visible_columns
    );
    configureRecordSheet_(
      workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.applied_jobs.name),
      JOB_PIPELINE_SETUP.sheets.applied_jobs.visible_columns
    );
    configureRecordSheet_(
      workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.archive.name),
      JOB_PIPELINE_SETUP.sheets.archive.visible_columns
    );
    configureSystemSheet_(
      workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.system.name)
    );
    applyReviewActionValidation_(
      workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.review_queue.name)
    );
    applyOutcomeValidation_(
      workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.applied_jobs.name)
    );
    workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.system.name).hideSheet();
    workbook.setActiveSheet(
      workbook.getSheetByName(JOB_PIPELINE_SETUP.sheets.review_queue.name)
    );
  } finally {
    lock.releaseLock();
  }
}

function configureRecordSheet_(sheet, visibleColumns) {
  ensureSheetCapacity_(
    sheet,
    JOB_PIPELINE_SETUP.maximumRows,
    JOB_PIPELINE_SETUP.recordFields.length
  );
  reconcileHeaders_(sheet, JOB_PIPELINE_SETUP.recordFields);
  sheet.setFrozenRows(1);
  sheet.getRange(1, 1, 1, JOB_PIPELINE_SETUP.recordFields.length)
    .setFontWeight('bold')
    .setBackground('#d9ead3');
  sheet.getRange(1, 1, Math.max(sheet.getMaxRows(), 2), JOB_PIPELINE_SETUP.recordFields.length)
    .setVerticalAlignment('top');

  const editable = new Set(JOB_PIPELINE_SETUP.editableColumns[sheet.getName()] || []);
  sheet.getProtections(SpreadsheetApp.ProtectionType.RANGE).forEach((protection) => {
    if (String(protection.getDescription() || '').startsWith('Job Pipeline generated:')) {
      protection.remove();
    }
  });

  JOB_PIPELINE_SETUP.recordFields.forEach((field, offset) => {
    const column = offset + 1;
    if (visibleColumns.includes(field)) {
      sheet.showColumns(column);
      sheet.setColumnWidth(
        column,
        ['generated_message', 'decision_reason', 'required_input', 'notes'].includes(field)
          ? 360
          : ['canonical_url', 'job_title'].includes(field) ? 240 : 140
      );
      if (['generated_message', 'decision_reason', 'required_input', 'notes'].includes(field)) {
        sheet.getRange(2, column, Math.max(sheet.getMaxRows() - 1, 1), 1)
          .setWrap(true);
      }
    } else {
      sheet.hideColumns(column);
    }
    if (!editable.has(field)) {
      const protection = sheet
        .getRange(1, column, Math.max(sheet.getMaxRows(), 2), 1)
        .protect()
        .setDescription('Job Pipeline generated:' + sheet.getName() + ':' + field);
      protection.setWarningOnly(true);
    }
  });

  if (!sheet.getFilter()) {
    sheet.getRange(1, 1, Math.max(sheet.getLastRow(), 1), JOB_PIPELINE_SETUP.recordFields.length)
      .createFilter();
  }
}

function configureSystemSheet_(sheet) {
  ensureSheetCapacity_(
    sheet,
    JOB_PIPELINE_SETUP.maximumRows,
    JOB_PIPELINE_SETUP.sheets.system.fields.length
  );
  reconcileHeaders_(sheet, JOB_PIPELINE_SETUP.sheets.system.fields);
  sheet.setFrozenRows(1);
  sheet.getRange(1, 1, 1, JOB_PIPELINE_SETUP.sheets.system.fields.length)
    .setFontWeight('bold')
    .setBackground('#eeeeee');
  sheet.getProtections(SpreadsheetApp.ProtectionType.SHEET).forEach((protection) => {
    if (protection.getDescription() === 'Job Pipeline generated:_System') {
      protection.remove();
    }
  });
  sheet.protect()
    .setDescription('Job Pipeline generated:_System')
    .setWarningOnly(true);
}

function ensureSheetCapacity_(sheet, minimumRows, minimumColumns) {
  if (sheet.getMaxRows() < minimumRows) {
    sheet.insertRowsAfter(
      sheet.getMaxRows(),
      minimumRows - sheet.getMaxRows()
    );
  }
  if (sheet.getMaxColumns() < minimumColumns) {
    sheet.insertColumnsAfter(
      sheet.getMaxColumns(),
      minimumColumns - sheet.getMaxColumns()
    );
  }
}

function reconcileHeaders_(sheet, headers) {
  const lastRow = sheet.getLastRow();
  const current = sheet
    .getRange(1, 1, 1, Math.max(sheet.getLastColumn(), headers.length))
    .getValues()[0]
    .map((value) => String(value || '').trim());
  const hasHeader = current.some(Boolean);
  if (hasHeader) {
    const actual = current.slice(0, headers.length);
    const extra = current.slice(headers.length).filter(Boolean);
    if (JSON.stringify(actual) !== JSON.stringify(headers) || extra.length > 0) {
      throw new Error(
        'Fresh setup found conflicting headers in sheet: ' +
        sanitizeSetupDiagnostic_(sheet.getName())
      );
    }
  } else {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  }
  if (lastRow > 1 && !hasHeader) {
    throw new Error('Fresh setup found data without headers');
  }
}

function applyReviewActionValidation_(sheet) {
  const statusColumn = JOB_PIPELINE_SETUP.recordFields.indexOf('pipeline_status') + 1;
  const actionColumn = JOB_PIPELINE_SETUP.recordFields.indexOf('user_action') + 1;
  const status = columnLetter_(statusColumn);
  const action = columnLetter_(actionColumn);
  const firstRow = 2;
  const formula =
    '=OR(' + action + firstRow + '="",' +
    'AND(' + status + firstRow + '="ready_to_apply",OR(' +
      action + firstRow + '="I Applied",' + action + firstRow + '="Skip")),' +
    'AND(' + status + firstRow + '="review_needed",OR(' +
      action + firstRow + '="Approve",' + action + firstRow + '="Deny")))';
  const validation = SpreadsheetApp.newDataValidation()
    .requireFormulaSatisfied(formula)
    .setAllowInvalid(false)
    .setHelpText('ready_to_apply: I Applied or Skip; review_needed: Approve or Deny')
    .build();
  sheet.getRange(
    firstRow,
    actionColumn,
    JOB_PIPELINE_SETUP.maximumRows - 1,
    1
  ).setDataValidation(validation);
}

function applyOutcomeValidation_(sheet) {
  const outcomeColumn = JOB_PIPELINE_SETUP.recordFields.indexOf('outcome') + 1;
  const validation = SpreadsheetApp.newDataValidation()
    .requireValueInList(JOB_PIPELINE_SETUP.outcomeValidation, true)
    .setAllowInvalid(false)
    .build();
  sheet.getRange(
    2,
    outcomeColumn,
    JOB_PIPELINE_SETUP.maximumRows - 1,
    1
  ).setDataValidation(validation);
}

function sanitizeSetupDiagnostic_(value) {
  return String(value || '')
    .replace(/https?:\/\/\S+/gi, '[url]')
    .replace(/[\r\n\t]+/g, ' ')
    .slice(0, 120);
}

function columnLetter_(column) {
  let value = column;
  let result = '';
  while (value > 0) {
    const remainder = (value - 1) % 26;
    result = String.fromCharCode(65 + remainder) + result;
    value = Math.floor((value - 1) / 26);
  }
  return result;
}
